### ISSUE TITLE
Create additional samples in Java

### ISSUE THREAD

**Issue by chadlung** [swagger-api/swagger-socket#2]
Most of the current samples are in Scala.  It would be nice to see more samples in Java.

**Comment by elakito** [comment]
the twitter-sample is in java and #20 just added a java version of the echo sample.
and the java version of this echo sample even uses cxf instead of jersey to illustrate another aspect.

So I think, we can close this issue as one can now get enough ideas and hints from those samples when creating their own scenario in their environment.

regards, aki
