### ISSUE TITLE
node client doesn't connect

### ISSUE THREAD

**Issue by danactive** [swagger-api/swagger-socket#48]
Two issues with the `swaggersocket-echo-node-client` sample
1. It's using a deprecated dependency `atmosphere-client`; now [atmosphere.js](https://github.com/Atmosphere/atmosphere.js-node)
2. After running `node echo-client.js` connection is unsuccessful

**Comment by elakito** [comment]
I could make it work by switching the jar.
I can update the whole library sometime and release swaggersocket-2.1.1 and push the corresponding swaggersocket.js to npm, but this will take some time because this will require updating most of the samples using the jquery version of swaggersocket and atmosphere.

**Comment by danactive** [comment]
I moved on, so don't put in the effort on my account.
